version: '3'
services:
  # spider network_mode: "host"
  spider1:
    image: includeno/originfinding-spider
    container_name: spider1
    network_mode: "host"
    environment:
      - server_port=8081
      - kafka_server=${kafka_server}
      - datasource=${datasource}
      - datasource_username=${datasource_username}
      - datasource_password=${datasource_password}
      - spider_count=8

  api:
    image: includeno/originfinding-sql
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - server_port=8080
      - kafka_server=${kafka_server}
      - datasource=${datasource}
      - datasource_username=${datasource_username}
      - datasource_password=${datasource_password}
      - redis_host=${redis_host}
      - redis_port=${redis_port}
      - redis_password=${redis_password}
      - redis_database=${redis_database}
