version: '3'
services:
  # spider network_mode: "host"
  spider1:
    image: includeno/originfinding-spider
    container_name: spider1
    network_mode: "host"
    environment:
      - consul_host=${consul_host}
      - consul_port=${consul_port}
      - consul_service_name=spider
      - consul_service_id=${machine_id}-spider1
      - server_port=8081


  spider2:
    image: includeno/originfinding-spider
    container_name: spider2
    network_mode: "host"
    environment:
      - consul_host=${consul_host}
      - consul_port=${consul_port}
      - consul_service_name=spider
      - consul_service_id=${machine_id}-spider2
      - server_port=8082

  api:
    image: includeno/originfinding-sql
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - consul_host=${consul_host}
      - consul_port=${consul_port}
      - consul_service_name=api
      - consul_service_id=${machine_id}-api
      - server_port=8080
      - kafka_server=${kafka_server}
      - datasource="jdbc:mysql://rm-uf646cc87yqoi7lu6lo.mysql.rds.aliyuncs.com:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
      - datasource_username=${datasource_username}
      - datasource_password=${datasource_password}
      - redis_host=${redis_host}
      - redis_port=${redis_port}
      - redis_password=${redis_password}
      - redis_database=${redis_database}
