#运行环境的启动方法 zookeeper
version: '2'
services:
  zookeeper:
    image: zookeeper:3.5.9
    container_name: zookeeper_container
    ports:
      - "2181:2181"
    networks:
      - app_net
  
  kafka01:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka_container_01
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=${zookeeper_ip}
      - KAFKA_ADVERTISED_PORT=9092
    networks:
      - app_net
    depends_on:
      - zookeeper

networks:
  app_net:
    driver: bridge