version: '3'
services:
  # spider network_mode: "host"
  spider1:
    image: includeno/originfinding-spider
    container_name: spider1
    network_mode: "host"
    environment:
      - consul_host=${consul_host}
      - consul_port=${consul_port}
      - consul_service_name=spider
      - consul_service_id=${machine_id}-spider1
      - server_port=8083
      - spider_count=8