version: '3'
services:
  # spider network_mode: "host"
  spider3:
    image: includeno/originfinding-spider
    container_name: spider3
    network_mode: "host"
    environment:
      - consul_host=${consul_host}
      - consul_port=${consul_port}
      - consul_service_name=spider
      - consul_service_id=${machine_id}-spider3
      - server_port=8081
      - kafka_server=${kafka_server}
      - datasource=${datasource}
      - datasource_username=${datasource_username}
      - datasource_password=${datasource_password}
      - spider_count=8